# Generated by Django 4.1.4 on 2023-01-22 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "url",
                    models.URLField(max_length=2048, primary_key=True, serialize=False),
                ),
                ("shop_url", models.URLField()),
                ("image_url", models.URLField()),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("lowest_price", models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                ("url", models.URLField(primary_key=True, serialize=False)),
                ("image", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductOffer",
            fields=[
                (
                    "product_buy_url",
                    models.URLField(max_length=2048, primary_key=True, serialize=False),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.product"
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.seller"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "product_offer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.productoffer",
                    ),
                ),
            ],
        ),
    ]
