# Generated by Django 4.1.4 on 2023-01-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CartMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=30)),
                ("session", models.CharField(max_length=255)),
                ("link", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
            ],
        ),
    ]
